LegoLeagueScorePages/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LegoLeagueScorePages.Controllers
{
    public class GameController : Controller
    {
        // GET: Game
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult WorldClass()
        {
            return View();
        }
    }
}

LegoLeagueScorePages/Views/Game/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="container">
    <h2>Scoring App Home</h2>
    <div class="panel col-sm-12">
        <p>Click the game you wish to calculate scores for:</p>
        @Html.ActionLink("World Class", "WorldClass", "Game")
    </div>
</div>

LegoLeagueScorePages/Views/Game/WorldClass.cshtml
@{
    ViewBag.Title = "World Class";
}

<div class="container">
    <h2><img src="~/Content/FLL_WorldClassRGB.jpg" />2014</h2>
    <div class="panel panel-info">
        <h4 class="panel-heading panel-title">Instructions</h4>
        <p class="panel-body">This page accurately simulates a scoring sheet. Simply answer the questions, and your score
        will be calculated at the bottom.</p>
    </div>
    <form action="" id="ScoreForm">
        <div class="col-md-6">
            <div class="panel panel-default">
                <h4 class="panel-heading panel-title">Opening Doors</h4>
                <div class="col-sm-offset-2">
                    <label for="openingDoors">Door opened by pushing down handle?</label>
                    <select id="openingDoors" name="openingDoors" class="form-control">
                        <option value="true">Yes</option>
                        <option value="false" selected="selected">No</option>
                    </select>
                </div>
            </div>
            <div class="panel panel-default">
                <h4 class="panel-heading panel-title">Cloud Access</h4>
                <div class="col-sm-offset-2">
                    <label for="cloudAccess">SD Card raised by inserting key</label>
                    <select id="cloudAccess" name="cloudAccess" class="form-control">
                        <option value="true">Yes</option>
                        <option value="false" selected="selected">No</option>
                    </select>
                </div>
            </div>
            <div class="panel panel-default">
                <h4 class="panel-heading panel-title">Community Learning</h4>
                <div class="col-sm-offset-2">
                    <label for="communityLearning">Knowledge &amp; skill loop no longer touching model?</label>
                    <select id="communityLearning" name="communityLearning" class="form-control">
                        <option value="true">Yes</option>
                        <option value="false" selected="selected">No</option>
                    </select>
                </div>
            </div>
            <div class="panel panel-default">
                <h4 class="panel-heading panel-title">Opening Doors</h4>
                <div class="col-sm-offset-2">
                    <label for="openingDoors">Door opened by pushing down handle?</label>
                    <select id="openingDoors" name="openingDoors" class="form-control">
                        <option value="true">Yes</option>
                        <option value="false" selected="selected">No</option>
                    </select>
                </div>
            </div>
            <div class="panel panel-default">
                <h4 class="panel-heading panel-title">Robotics Competition</h4>
                <div class="col-sm-offset-2">
                    <label for="roboticsCompetition">Insert in place and loop no longer touching model?</label>
                    <select id="roboticsCompetition" name="roboticsCompetition" class="form-control">
                        <option value="true">Yes</option>
                        <option value="false" selected="selected">No</option>
                    </select>
                </div>
            </div>
            <div class="panel panel-default">
                <h4 class="panel-heading panel-title">Using the Right Senses</h4>
                <div class="col-sm-offset-2">
                    <label for="usingSenses">Loop released by moving slider and no longer touching model?</label>
                    <select id="usingSenses" name="usingSenses" class="form-control">
                        <option value="true">Yes</option>
                        <option value="false" selected="selected">No</option>
                    </select>
                </div>
            </div>
            <div class="panel panel-default">
                <h4 class="panel-heading panel-title">Thinking Outside the Box</h4>
                <div class="col-sm-offset-2">
                    <label for="outsideBox1">Idea model no longer touching box model?</label>
                    <select id="outsideBox1" name="outsideBox1" class="form-control">
                        <option value="true">Yes</option>
                        <option value="false" selected="selected">No</option>
                    </select>
                    <label for="outsideBox2">Bulb facing up?</label>
                    <select id="outsideBox2" name="outsideBox2" class="form-control">
                        <option value="true">Yes</option>
                        <option value="false" selected="selected">No</option>
                    </select>
                </div>
            </div>
            <div class="panel panel-default">
                <h4 class="panel-heading panel-title">Remote Communication/Learning</h4>
                <div class="col-sm-offset-2">
                    <label for="remoteCommunication">Slider pulled west?</label>
                    <select id="remoteCommunication" name="remoteCommunication" class="form-control">
                        <option value="true">Yes</option>
                        <option value="false" selected="selected">No</option>
                    </select>
                </div>
            </div>
            <div class="panel panel-default">
                <h4 class="panel-heading panel-title">Penalties</h4>
                <div class="col-sm-offset-2">
                    <label for="penalties">Number of penalty markers at end of match?</label>
                    <select id="penalties" name="penalties" class="form-control">
                        <option value="0" selected="selected">0</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <h4 class="panel-heading panel-title">Search Engine</h4>
                <div class="col-sm-offset-2">
                    <label for="searchEngine1">Color wheel spun by moving slider?</label>
                    <select id="searchEngine1" name="searchEngine1" class="form-control">
                        <option value="true">Yes</option>
                        <option value="false" selected="selected">No</option>
                    </select>
                    <label for="searchEngine2">Correct loop is no longer touching model and all other loops touching model?</label>
                    <select id="searchEngine2" name="searchEngine2" class="form-control">
                        <option value="true">Yes</option>
                        <option value="false" selected="selected">No</option>
                    </select>
                </div>
            </div>
            <div class="panel panel-default">
                <h4 class="panel-heading panel-title">Sports</h4>
                <div class="col-sm-offset-2">
                    <label for="sports1">Shot taken from behind black lines?</label>
                    <select id="sports1" name="sports1" class="form-control">
                        <option value="true">Yes</option>
                        <option value="false" selected="selected">No</option>
                    </select>
                    <label for="sports2">Shot is a goal?</label>
                    <select id="sports2" name="sports2" class="form-control">
                        <option value="true">Yes</option>
                        <option value="false" selected="selected">No</option>
                    </select>
                </div>
            </div>
            <div class="panel panel-default">
                <h4 class="panel-heading panel-title">Reverse Engineering</h4>
                <div class="col-sm-offset-2">
                    <label for="revEngineer1">Basket brought to base?</label>
                    <select id="revEngineer1" name="revEngineer1" class="form-control">
                        <option value="true">Yes</option>
                        <option value="false" selected="selected">No</option>
                    </select>
                    <label for="revEngineer2">Copy of provided model in base?</label>
                    <select id="revEngineer2" name="revEngineer2" class="form-control">
                        <option value="true">Yes</option>
                        <option value="false" selected="selected">No</option>
                    </select>
                </div>
            </div>
            <div class="panel panel-default">
                <h4 class="panel-heading panel-title">Adapting to Changing Conditions</h4>
                <div class="col-sm-offset-2">
                    <label for="adapting">Model rotated 90&deg;-ish from setup?</label>
                    <select id="adapting" name="adapting" class="form-control">
                        <option value="true">Yes</option>
                        <option value="false" selected="selected">No</option>
                    </select>
                </div>
            </div>
            <div class="panel panel-default">
                <h4 class="panel-heading panel-title">Apprenticeship</h4>
                <div class="col-sm-offset-2">
                    <label for="apprenticeship1">Model presented to referee before match start?</label>
                    <select id="apprenticeship1" name="apprenticeship1" class="form-control">
                        <option value="true">Yes</option>
                        <option value="false" selected="selected">No</option>
                    </select>
                    <label for="apprenticeship2">Model touching white circle?</label>
                    <select id="apprenticeship2" name="apprenticeship2" class="form-control">
                        <option value="true">Yes</option>
                        <option value="false" selected="selected">No</option>
                    </select>
                </div>
            </div>
            <div class="panel panel-default">
                <h4 class="panel-heading panel-title">Engagement</h4>
                <div class="col-sm-offset-2">
                    <label for="engagement1">Lever engaged?</label>
                    <select id="engagement1" name="engagement1" class="form-control">
                        <option value="true">Yes</option>
                        <option value="false" selected="selected">No</option>
                    </select>
                    <label for="engagement2">Dial location at end of match?</label>
                    <select id="engagement2" name="engagement2" class="form-control">
                        <option value="false" selected="selected">N/A</option>
                        <option value="10">10</option>
                        <option value="16">16</option>
                        <option value="22">22</option>
                        <option value="28">28</option>
                        <option value="34">34</option>
                        <option value="40">40</option>
                        <option value="46">46</option>
                        <option value="52">52</option>
                        <option value="58">58</option>
                    </select>
                    <label for="engagement3">Major turns towards next mark?</label>
                    <select id="engagement3" name="engagement3" class="form-control">
                        <option value="false" selected="selected">N/A</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                    </select>
                </div>
            </div>
            <div class="panel panel-default">
                <h4 class="panel-heading panel-title">Project Based Learning</h4>
                <div class="col-sm-offset-2">
                    <label for="pbl">Number of loops hanging on model at end of match?</label>
                    <select id="pbl" name="pbl" class="form-control">
                        <option value="false" selected="selected">0</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                        <option value="8">8</option>
                    </select>
                </div>
            </div>
        </div>
    </form>
 </div>